import { demoOrder, type Order } from "@/lib/orders";

// Made-up sample orders for Mimi's page (the names are not real customers).
const base = { colours: "photo" as const, when: "No rush", photos: [], updates: [] as Order["updates"], sample: true };

export const sampleOrders: (Order & { due: string; dueTone: "normal" | "soon" | "late"; ago: string })[] = [
  {
    ...base,
    id: "MIMI-2411",
    code: "c4h9wq",
    createdAt: "2026-10-03",
    piece: { name: "From her photo", image: "/images/ideas/daisy-ruffle-crochet-set.jpg", source: "photo" },
    photos: ["/images/ideas/daisy-ruffle-crochet-set.jpg"],
    size: "M",
    name: "Chioma",
    phone: "+234 803 000 0001",
    state: "Lagos",
    area: "Yaba",
    stage: 0,
    updates: [{ stage: 0, note: "Request sent with her size and colours.", at: "2h ago" }],
    due: "Just now",
    dueTone: "normal",
    ago: "2h ago",
  },
  {
    ...base,
    id: "MIMI-2410",
    code: "t7b2kx",
    createdAt: "2026-10-02",
    piece: { name: "Royal Wave Crochet Shirt", image: "/images/products/royal-wave-crochet-shirt-1.jpg", slug: "royal-wave-crochet-shirt", source: "product", price: 70000 },
    size: "XL",
    name: "Tobi",
    phone: "+234 803 000 0002",
    state: "Lagos",
    area: "Lekki",
    stage: 0,
    updates: [{ stage: 0, note: "Request sent from the Royal Wave product page, size XL.", at: "Yesterday" }],
    due: "Yesterday",
    dueTone: "normal",
    ago: "yesterday",
  },
  {
    ...base,
    id: "MIMI-2408",
    code: "k3m8pz",
    createdAt: "2026-09-30",
    piece: { name: "Sunshine Mini Dress", image: "/images/products/sunshine-crochet-mini-dress-1.jpg", slug: "sunshine-crochet-mini-dress", source: "product", price: 45000 },
    size: "L",
    name: "Kemi",
    phone: "+234 803 000 0003",
    state: "Oyo",
    area: "Bodija, Ibadan",
    stage: 1,
    price: 50000,
    readyBy: "Fri 16 Oct",
    depositPaid: true,
    updates: [
      { stage: 0, note: "Request sent with her size and colours.", at: "30 Sep" },
      { stage: 1, note: "₦50,000, ready by Fri 16 Oct. Deposit ₦30,000.", at: "1 Oct" },
    ],
    due: "Start by Thu",
    dueTone: "soon",
    ago: "3 days ago",
  },
  {
    ...base,
    id: "MIMI-2403",
    code: "a9d4vr",
    createdAt: "2026-09-20",
    piece: { name: "Stasia Dress", image: "/images/products/lilac-ruffle-tube-dress-1.jpg", slug: "lilac-ruffle-tube-dress", source: "product", price: 60000 },
    size: "S",
    name: "Ada",
    phone: "+234 803 000 0004",
    state: "Rivers",
    area: "Rumuola, Port Harcourt",
    stage: 2,
    price: 60000,
    readyBy: "Mon 28 Sep",
    depositPaid: true,
    updates: [
      { stage: 0, note: "Request sent with her size and colours.", at: "20 Sep" },
      { stage: 1, note: "Price agreed with Mimi on WhatsApp.", at: "21 Sep" },
      { stage: 2, note: "Ruffles on the first tier are done.", at: "26 Sep" },
    ],
    due: "2 days late",
    dueTone: "late",
    ago: "2 weeks ago",
  },
  { ...demoOrder, due: "In 8 days", dueTone: "normal", ago: "4 days ago" },
  {
    ...base,
    id: "MIMI-2401",
    code: "f5n6hs",
    createdAt: "2026-09-15",
    piece: { name: "Sasha Ruffle Set", image: "/images/products/candy-bloom-ruffle-set-1.jpg", slug: "candy-bloom-ruffle-set", source: "product", price: 40000 },
    size: "M",
    name: "Funmi",
    phone: "+234 803 000 0006",
    state: "FCT Abuja",
    area: "Wuse 2",
    stage: 3,
    price: 40000,
    readyBy: "Fri 2 Oct",
    depositPaid: true,
    updates: [
      { stage: 0, note: "Request sent.", at: "15 Sep" },
      { stage: 1, note: "Price agreed with Mimi on WhatsApp.", at: "16 Sep" },
      { stage: 2, note: "Halfway there.", at: "24 Sep" },
      { stage: 3, note: "All done! Photos on WhatsApp.", at: "2 Oct", photo: "/images/products/candy-bloom-ruffle-set-1.jpg" },
    ],
    due: "Send today",
    dueTone: "soon",
    ago: "2 weeks ago",
  },
];
